base: --no-source --color --format pretty -p html_report -pjson_report
default: --profile qa

qa: --profile base PROFILE=qa
preprod: --profile base PROFILE=preprod
prod: --profile base PROFILE=prod
local: --profile base PROFILE=local


html_report: --format progress --format html --out=report/features_report.html  
bvt: --tags @bvt
json_report: --format progress --format json --out=report/features_report.json
